from typing import List, Sequence, Tuple

class ClickResult:
    @property
    def coords(self) -> List[Tuple[float, float]]: ...
    @property
    def confidences(self) -> List[float]: ...
    @property
    def k(self) -> int: ...
    @property
    def m(self) -> int: ...

class SlideResult:
    @property
    def distance(self) -> int: ...
    @property
    def encrypted_track(self) -> str: ...

class Solver:
    def __init__(self) -> None: ...
    def solve(self, image: bytes, conf_threshold: float = 0.5) -> ClickResult: ...

def solve_slide(bg: bytes, fullbg: bytes) -> SlideResult: ...
def click_w(coords: Sequence[Tuple[float, float]], gt: str, challenge: str) -> str: ...
def slide_w(
    distance: int,
    encrypted_track: str,
    gt: str,
    challenge: str,
    c: Sequence[int],
    s: str,
) -> str: ...
