from typing import List, Optional, Tuple

class Detection:
    @property
    def bbox(self) -> Tuple[float, float, float, float]: ...
    @property
    def confidence(self) -> float: ...
    @property
    def class_id(self) -> int: ...

class DetectResult:
    @property
    def detections(self) -> List[Detection]: ...
    @property
    def answer_features(self) -> List[List[float]]: ...
    @property
    def prompt_features(self) -> List[List[float]]: ...
    @property
    def prompt_box(self) -> Optional[Tuple[float, float, float, float]]: ...

class Detector:
    def __init__(self) -> None: ...
    def detect(self, image: bytes, conf_threshold: float = 0.1) -> DetectResult: ...
